apiVersion: v2
name: ${{ values.gameName }}
description: ${{ values.description }}
type: application
version: 0.1.0
appVersion: "${{ values.appVersion }}"
keywords:
  - ${{ values.gameName }}
  - gameserver
  - minato
home: https://github.com/7k-minato/minato-games
sources:
  - https://github.com/7k-minato/minato-games
  - https://github.com/7k-minato/minato
maintainers:
  - name: 7K-Minato
    email: dev@7kgroup.com
