apiVersion: operator.minato.io/v1
kind: GameServer
metadata:
  name: minecraft-server-1
  namespace: minato
spec:
  profile: minecraft-paper
  env:
    EULA: "true"
    SERVER_NAME: "My Minecraft Server"
    MEMORY: "4G"
