{{- if and .Values.security.rcon.password (not .Values.security.rcon.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minato-games.fullname" . }}-rcon
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minato-games.labels" . | nindent 4 }}
type: Opaque
stringData:
  RCON_PASSWORD: {{ .Values.security.rcon.password | quote }}
{{- end }}
