apiVersion: v2
name: palworld
description: Palworld dedicated server for Minato
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - palworld
  - gameserver
  - minato
home: https://github.com/7k-minato/minato-games
sources:
  - https://github.com/7k-minato/minato-games
  - https://github.com/7k-minato/minato
maintainers:
  - name: 7K Group
    email: dev@7kgroup.com
dependencies:
  - name: minato-games-library
    version: "0.0.0-test"
    repository: "oci://harbor.7kgroup.org/7kminato/charts"
    condition: library.enabled
