apiVersion: v2
name: cs2
description: Counter-Strike 2 dedicated server for Minato
type: application
version: 0.1.2
appVersion: latest
keywords:
  - cs2
  - counter-strike
  - gameserver
  - minato
home: https://github.com/7k-minato/minato-games
sources:
  - https://github.com/7k-minato/minato-games
  - https://github.com/7k-minato/minato
maintainers:
  - name: 7K Group
    email: dev@7kgroup.com
